spring:
  datasource:
    url: ${VAULTNOTE_DATABASE_URL:jdbc:postgresql://localhost:5432/vault_note}
    username: ${VAULTNOTE_DATABASE_USERNAME:user}
    password: ${VAULTNOTE_DATABASE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: vaultnote
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: vaultnote
