spring:
  config:
    import: optional:classpath:application-local-secrets.yaml
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
            client-settings:
              require-proof-key: true
  datasource:
    url: ${VAULTNOTE_DATABASE_URL:jdbc:postgresql://localhost:5432/vault_note}
    username: ${VAULTNOTE_DATABASE_USERNAME:user}
    password: ${VAULTNOTE_DATABASE_PASSWORD:password}

app:
  jwt:
    access-token-ttl: P3D
  refresh-token:
    ttl: P7D
