spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: vaultnote
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: vaultnote
